In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold

In [4]:
df = pd.read_csv('yeast_pairs.tsv', sep='\t', header=None)
df.columns = ['p1', 'p2', 'label']
df = df.sample(frac=1).reset_index(drop=True)
df

           p1      p2  label
0      P38957  P25659      0
1      P53914  P22139      1
2      P39926  P00044      1
3      Q06208  P11076      0
4      Q08979  Q02884      1
...       ...     ...    ...
11183  P37370  P12683      0
11184  Q08215  Q00578      1
11185  Q08723  P38217      1
11186  P53900  P17157      1
11187  P53863  P42841      0

[11188 rows x 3 columns]

In [22]:
skf = StratifiedKFold(n_splits=5, random_state=42, shuffle=True)
train_test = []
for train_index, test_index in skf.split(df[['p1', 'p2']], df['label']):
    train_test.append((train_index, test_index))

for i in range(5):
    train = df.loc[train_test[i][0]]
    test = df.loc[train_test[i][1]]
    train.to_csv(f'd-script/yeast_train{i}.tsv', sep='\t', header=None, index=None)
    test.to_csv(f'd-script/yeast_test{i}.tsv', sep='\t', header=None, index=None)